name: README Generate

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: "3.9"
          cache: "pip"
      - run: pip install -r requirements.txt
      - name: Markdown Generation
        run: |
          jupyter nbconvert --execute --to markdown main.ipynb
      - name: Rename MD file
        run: |
          mv main.md README.md
      - uses: EndBug/add-and-commit@v9
        with:
          add: "README.md"
          author_name: Eunchurn Park
          author_email: eunchurn.park@gmail.com
